export const MESSAGES = {
  // Authentication & User Management
  LOGIN_SUCCESS: "Login successful.",
  LOGIN_FAILED: "Login failed. Please check your credentials.",
  INVALID_CREDENTIALS: "Invalid credentials.",
  //   INVALID_CREDENTIALS: "Invalid email or password.",
  UNAUTHORIZED_ACCESS: "Unauthorized access. Please log in.",
  FORBIDDEN: "You do not have permission to perform this action.",
  USER_NOT_FOUND: "User does not exist.",
  NOT_FOUND: "Data Not Found",
  USER_ALREADY_EXISTS: "User with this email already exists.",
  ACCOUNT_VERIFIED: "Account successfully verified.",
  ACCOUNT_NOT_VERIFIED: "Your account is not verified yet.",
  LOGOUT_SUCCESS: "Logged out successfully.",
 TRANSACTION_FAILED:'Transaction Failed',
 PAYMENT_IN_PROGRESS:'Payment already initiated for this loan by you. Please complete or cancel the previous payment.',
 PAYMENT_FAILED:'payment failed',
  // Registration & Profile
  REGISTRATION_SUCCESS: "Registration successful.",
  REGISTRATION_FAILED: "Registration failed. Please try again.",
  PROFILE_UPDATED: "Profile updated successfully.",
  PROFILE_UPDATE_FAILED: "Failed to update profile.",
  PASSWORD_CHANGED: "Password changed successfully.",
  PASSWORD_RESET_SENT: "Password reset email sent.",
  PASSWORD_RESET_SUCCESS: "Password reset successful.",
  PASSWORD_RESET_FAILED: "Failed to reset password.",
CREATED:'Created Successfully',
  // Notifications & Reminders
  EMAIL_VERIFICATION_SENT: "Verification email sent successfully.",
  EMAIL_VERIFICATION_SUCCESS: "Email successfully verified.",
  EMAIL_VERIFICATION_FAILED: "Failed to verify email.",
  OTP_SENT: "OTP sent successfully.",
  OTP_VERIFIED: "OTP verified successfully.",
  OTP_INVALID: "Invalid OTP. Please try again.",

  // DATA SENT
  DATA_SENT_SUCCESS: "Data sent successfully.",
  DATA_FETCH_SUCCESS: "Data fetched successfully.",
 ALREADY_EXISTS:'data alredy exist',
    UPDATE_SUCCESS:'updated Successfully',
  SERVER_ERROR: "An unexpected error occurred.",
  BAD_REQUEST: "Invalid request. Please check the input data.",
  RESOURCE_NOT_FOUND: "Requested resource not found.",
  VALIDATION_ERROR: "Validation failed. Please check your input.",
   TOKEN_EXPIRED: "Session expired login again",
  TOKEN_BLACKLISTED: "Session is no longer valid",
    INVALID_TOKEN: "Invalid session please login again",


}
