 


export const TYPES = {
  PaymentRepository: Symbol.for("PaymentRepository"),
  AuthUserService: Symbol.for("AuthUserService"),
  PasswordService:Symbol.for('PasswordService'),
  EmailService:Symbol.for('EmailService'),
  JwtService:Symbol.for('JwtService'),
  RedisTokenRepository:Symbol.for("RedisTokenRepository"),
  RefreshTokenRepository: Symbol.for("RefreshTokenRepository"),
  WorkingDetailsRepository: Symbol.for("WorkingDetailsRepository"),
  WorkerAggregation: Symbol.for("WorkerAggregation"),
  WorkerRepository: Symbol.for("WorkerRepository"),
  AuthWorkerService:Symbol.for("AuthWorkerService"),
  CloudinaryService:Symbol.for("CloudinaryService"),
  GetWorkingDetails:Symbol.for("GetWorkingDetails"),
  UpdateWorkingDetails:Symbol.for("UpdateWorkingDetails"),
  UpdateUserDetails:Symbol.for("UpdateUserDetails"),
  LoginService:Symbol.for("LoginService"),
  RegisterService:Symbol.for("RegisterService"),
  OtpService:Symbol.for("OtpService"),
  GoogleService:Symbol.for("GoogleService"),
  GetService:Symbol.for("GetService"),
  IsVerified:Symbol.for("IsVerified"),
  GetUserProfileDetails:Symbol.for("GetUserProfileDetails"),
  AuthUserRepository: Symbol.for("AuthUserRepository"),
  OtpRepository:Symbol.for('OtpRepository'),
  AdminRepository:Symbol.for('AdminRepository'),
  AuthAdminService:Symbol.for('AuthAdminService'),
  TokenService:Symbol.for('TokenService'),
  GoogleAuthService:Symbol.for('GoogleAuthService'),
  ManagementAdminService:Symbol.for('ManagementAdminService'),
  ResetPassword:Symbol.for('ResetPassword'),
  ServiceRepository:Symbol.for('ServiceRepository'),
  WorkerHelperService:Symbol.for('WorkerHelperService'),
  GetNearByWorkers:Symbol.for('GetNearByWorkers'),
  DateConversionService:Symbol.for('DateConversionService'),
  BookingRepository:Symbol.for('BookingRepository'),
  GetWorkerAvailability:Symbol.for('GetWorkerAvailability'),
  ServiceDetails:Symbol.for('ServiceDetails'),
  ProfileManagement:Symbol.for('ProfileManagement'),
  WorkingDetailsManagement:Symbol.for('WorkingDetailsManagement'),
  WorkingHelper:Symbol.for('WorkingHelper'),
  AddressRepository:Symbol.for('AddressRepository'),
  BookingService:Symbol.for('BookingService'),
  StripeService:Symbol.for('StripeService'),

}; 